### ISSUE TITLE
Will output questions 1 and 2

### ISSUE THREAD

**Issue by WeiduKe** [ThisKarolGajda/OpEconomy#1]
I used the 1.4.0 version. When the server is turned on, it will output a 1, and after a while, it will output 2 forever. The player is visible.

**Comment by ThisKarolGajda** [comment]
Can you describe it more, what's happening?

**Comment by WeiduKe** [comment]
I am using the paper1.17 core. When I load the 1.4.0 version to start the console, it will output the number "1", and then output the number "2", and the number 2 will continue to execute. Please forgive my English, I am from China!

**Comment by WeiduKe** [comment]
> 你能描述一下吗？

Sorry, I cannot provide images. Because I am using version 1.3.0.

**Comment by ThisKarolGajda** [comment]
Okay. I think what is causing this problem.
Will be fixed in 2 hours maximum.

**Comment by ThisKarolGajda** [comment]
**Okay!**
Thank you for informing us.
Bug is now fixed. If you encounter any other bugs, report them, so I can quickly fix them!
Thank you once again, for being a part in OpEconomy!

[1.4.1 Version](https://github.com/ThisKarolGajda/OpEconomy/releases/tag/1.4.1)

**Comment by WeiduKe** [comment]
> **好！**
> 谢谢你通知我们。
> 错误现已修复。如果您遇到任何其他错误，请报告它们，以便我可以快速修复它们！
> 再次感谢您成为 Ope 经济的一部分！
> 
> [1.4.1 版本](https://github.com/ThisKarolGajda/OpEconomy/releases/tag/1.4.1)

Thanks for the fix!
